version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.8.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  passenger-service:
    build: ./passenger-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - mongodb

  ticketing-service:
    build: ./ticketing-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - mongodb

  payment-service:
    build: ./payment-service
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - mongodb

  notification-service:
    build: ./notification-service
    ports:
      - "8084:8084"
    depends_on:
      - kafka

  admin-service:
    build: ./admin-service
    ports:
      - "8085:8085"
    depends_on:
      - kafka
      - mongodb

  transport-service:
    build: ./transport-service
    ports:
      - "8086:8086"
    depends_on:
      - kafka
      - mongodb

volumes:
  mongo-data:
