[package]
org = "transport_system"
name = "service_template"
version = "1.0.0"
distribution = "2201.8.5"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "http"
version = "2.10.10"

[[dependency]]
org = "ballerina"
name = "log"
version = "2.9.1"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "1.7.0"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.4.0"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "2.7.0"

[[dependency]]
org = "ballerina"
name = "jwt"
version = "2.10.0"

[[dependency]]
org = "ballerina"
name = "regex"
version = "1.4.3"

[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "4.1.0"

[[dependency]]
org = "ballerinax"
name = "kafka"
version = "3.7.0"

[[dependency]]
org = "ballerinax"
name = "redis"
version = "3.0.0"

[tool.bal]
observability.enabled = true
observability.provider = "jaeger"
